#!/usr/bin/env python3
"""Taste extraction — the framework's front door (PRD §7.3).

Taste cannot be written down directly; it is derived from reactions.
This tool runs the extraction interview: structured questions plus
forced choices between real rendered candidates (text tier — text is
a render). It records the raw answers and emits a DRAFT taste file
for the author to prune.

The loop this tool starts:
    elicit (this tool) → compile candidate rules → validate on a blind
    set (pipeline/author_agent.py blindset) → divergence = bug list →
    amend → repeat, until the taste file predicts the author's blind
    choices >= 90%.

Usage:
    python3 pipeline/extract_taste.py --tree mytree --author alice
    python3 pipeline/extract_taste.py --tree mytree --author alice --answers prepared.yaml
    ... --compile     # additionally synthesize candidate rules via the Claude API

Interactive answers end with a single '.' on its own line. With
--answers, responses are read from a yaml file (see the printed
template) instead of stdin — useful for re-runs and testing.
"""

import argparse
import datetime
import json
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
MODEL = "claude-opus-4-8"

QUESTIONS = [
    ("absolutes", "What must ALWAYS be true of a scene for you to keep it? Name the one thing you would never waive."),
    ("absolutes", "Describe the last scene (any medium) you deleted or skipped. What exactly made it deletable?"),
    ("antagonism", "Where does conflict come from in stories you love? Describe a villain you found satisfying, and one you found boring — what separated them?"),
    ("resolution", "Recall a conflict resolution that delighted you. What mechanism resolved it — force, cleverness, exposure, luck, empathy, absurdity?"),
    ("resolution", "When is it acceptable for a protagonist to simply WIN — to dominate the opposition? What has to be true first?"),
    ("endings", "How should an episode end? What separates a hook that pulls you forward from a cheap tease?"),
    ("decisions", "When you can't choose between two versions of a scene, what do you do — argue it out, or make both and feel? Describe the last time each happened."),
    ("decisions", "What does your wince feel like — the moment you know something is wrong before you can say why? What usually triggers it?"),
    ("rejection", "A collaborator's idea doesn't fit your story. What happens to it? Walk through what you actually do."),
    ("texture", "Name three works whose *taste* (not plot) you'd steal, and the single quality you'd take from each."),
]

FORCED_CHOICES = [
    {
        "id": "fc-01",
        "a": "The tyrant sneers as he signs the eviction order: 'Because I can.' The hero's family is cast out into the storm as he laughs.",
        "b": "The clerk stamps the eviction order without looking up. 'Forty years I've stamped these. You know what happens if I don't stamp them?' A pause. 'Neither do I.' He stamps the next one.",
    },
    {
        "id": "fc-02",
        "a": "She wins the argument by producing the one document that proves him wrong. He concedes, humiliated, and the council votes her way.",
        "b": "Mid-argument she reads his figures aloud in the voice of the pompous auditor they both survived years ago. He fights the grin and loses. 'Fine. FINE. Read mine again, I can't hear it anymore either.' They redo the figures together.",
    },
    {
        "id": "fc-03",
        "a": "Episode ends: the messenger arrives, breathless — 'The bridge... the bridge is gone.' Smash to black.",
        "b": "Episode ends: a slow pan over the peaceful valley at dusk, the day's work done. Tomorrow is another day. Fade out.",
    },
]

DRAFT_HEADER = """# Taste file — {tree} — {author} — v0.1 DRAFT
#
# Generated by pipeline/extract_taste.py on {date} from the raw
# interview at {answers_path}.
# This is NOT a taste file yet. Prune it: keep only rules you would
# defend against your own future self, number them R1..Rn, delete the
# rest. Then validate against a blind set (taste/blindsets/README.md)
# and amend until agreement >= 90%.
"""


def ask(prompt: str) -> str:
    print(f"\n\033[1m{prompt}\033[0m\n(end with a single '.' on its own line)")
    lines = []
    for line in sys.stdin:
        if line.strip() == ".":
            break
        lines.append(line.rstrip("\n"))
    return "\n".join(lines).strip()


def run_interview(prepared: dict | None) -> dict:
    answers, choices = {}, []
    for i, (section, q) in enumerate(QUESTIONS, 1):
        qid = f"q{i:02d}"
        if prepared:
            answers[qid] = {"section": section, "question": q, "answer": str(prepared.get("answers", {}).get(qid, ""))}
        else:
            answers[qid] = {"section": section, "question": q, "answer": ask(f"[{i}/{len(QUESTIONS)}] ({section}) {q}")}
    for fc in FORCED_CHOICES:
        if prepared:
            rec = prepared.get("choices", {}).get(fc["id"], {})
            pick, why = str(rec.get("pick", "")), str(rec.get("why", ""))
        else:
            print(f"\n\033[1mForced choice {fc['id']} — feel, don't reason (R4). Which do you keep?\033[0m")
            print(f"\n  (a) {fc['a']}\n\n  (b) {fc['b']}\n")
            pick = ""
            while pick not in ("a", "b"):
                pick = input("a or b? ").strip().lower()
            why = input("one line — why (or what winced): ").strip()
        choices.append({"id": fc["id"], "a": fc["a"], "b": fc["b"], "pick": pick, "why": why})
    return {"answers": answers, "choices": choices}


def draft_rules(interview: dict) -> str:
    out = []
    by_section: dict = {}
    for qid, rec in interview["answers"].items():
        by_section.setdefault(rec["section"], []).append(rec)
    for section, recs in by_section.items():
        out.append(f"\n## Draft rules — {section}\n")
        for rec in recs:
            answer = rec["answer"] or "(no answer)"
            out.append(f"> **Q:** {rec['question']}\n>\n> **A:** {answer}\n>\n> **Candidate rule:** _(distill the answer above into one testable sentence)_\n")
    out.append("\n## Observed preferences (forced choices)\n")
    for c in interview["choices"]:
        out.append(f"- `{c['id']}`: kept **({c['pick']})** — {c['why'] or '(no reason recorded)'}")
    return "\n".join(out)


COMPILE_SCHEMA = {
    "type": "object",
    "properties": {
        "rules": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {"type": "string", "description": "R1, R2, ..."},
                    "name": {"type": "string", "description": "Two-to-four word rule name"},
                    "rule": {"type": "string", "description": "One or two testable sentences, in the author's own vocabulary where possible"},
                    "evidence": {"type": "string", "description": "Which answers/choices this rule is derived from, e.g. 'q03, fc-01'"},
                },
                "required": ["id", "name", "rule", "evidence"],
                "additionalProperties": False,
            },
        }
    },
    "required": ["rules"],
    "additionalProperties": False,
}


def compile_rules(interview: dict) -> str:
    import anthropic

    client = anthropic.Anthropic()
    response = client.messages.create(
        model=MODEL,
        max_tokens=16000,
        thinking={"type": "adaptive"},
        output_config={"format": {"type": "json_schema", "schema": COMPILE_SCHEMA}},
        system=(
            "You compile an author's raw taste-extraction interview into candidate taste rules. "
            "Rules must be testable against candidate scenes, few (4-8), derived only from what the "
            "author actually said or chose — never generic writing advice. Preserve the author's own "
            "words where they are vivid. Contradictions between answers become a rule about the tension, "
            "not a silent resolution."
        ),
        messages=[{"role": "user", "content": yaml.safe_dump(interview, sort_keys=False, allow_unicode=True)}],
    )
    if response.stop_reason == "refusal":
        raise SystemExit("model refused; see stop_details")
    data = json.loads(next(b.text for b in response.content if b.type == "text"))
    lines = ["\n## Compiled candidate rules (machine-drafted — prune ruthlessly)\n"]
    for r in data["rules"]:
        lines.append(f"### {r['id']} — {r['name']}\n{r['rule']}\n*(evidence: {r['evidence']})*\n")
    return "\n".join(lines)


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--tree", required=True, help="tree id, e.g. sapling")
    p.add_argument("--author", required=True, help="author handle")
    p.add_argument("--answers", help="yaml file with prepared answers (non-interactive)")
    p.add_argument("--compile", action="store_true", help="also synthesize candidate rules via the Claude API")
    args = p.parse_args()

    prepared = yaml.safe_load(Path(args.answers).read_text()) if args.answers else None
    interview = run_interview(prepared)

    date = datetime.date.today().isoformat()
    interviews_dir = REPO / "taste" / "interviews"
    interviews_dir.mkdir(parents=True, exist_ok=True)
    answers_path = interviews_dir / f"{args.tree}.{args.author}.{date}.yaml"
    answers_path.write_text(
        "# Raw taste-extraction interview — the diff history of a soul starts here\n"
        + yaml.safe_dump({"tree": args.tree, "author": args.author, "date": date, **interview},
                         sort_keys=False, allow_unicode=True)
    )

    draft = DRAFT_HEADER.format(tree=args.tree, author=args.author, date=date,
                                answers_path=answers_path.relative_to(REPO))
    draft += draft_rules(interview)
    if args.compile:
        draft += compile_rules(interview)
    draft_path = REPO / "taste" / f"{args.tree}.{args.author}.v0.1-draft.md"
    draft_path.write_text(draft)

    print(f"✓ interview  → {answers_path.relative_to(REPO)}")
    print(f"✓ draft      → {draft_path.relative_to(REPO)}")
    print("next: prune the draft into a real taste file, then validate with "
          "`python3 pipeline/author_agent.py blindset ...` (see taste/blindsets/README.md)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
